config/routes.rb
Rails.application.routes.draw do
  
  resources :upcoming_books
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts do
    resources :comments
  end  
  
  root to: 'pages#home'
  get '/pages/', to: 'pages#home' 
  
  devise_for :users

  get '/search', to: "posts#search"
  # get '/upcoming_book', to: 'posts#upcoming_book'

  # resources :booksdocs, only: [:index, :new, :create, :destroy]
   # root "booksdocs#index"

#   devise_for :users do
#   get '/users/sign_out' => 'devise/sessions#destroy'
# end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  

  belongs_to :user
  validates :title, :description, :author, :b_subject, :image, :attachment, presence: true
  has_one_attached :image
  #has_one_attached :avatar
  has_one_attached :attachment
  
  has_many :comments, dependent: :destroy


  mount_uploader :attachment, AttachmentUploader 
   
  #validates :name, presence: true 
  # mount_uploader :attachment, AttachmentUploader 

  # scope : sort, -> { post(created_at: :desc) }

end

app/models/upcoming_book.rb
class UpcomingBook < ApplicationRecord
	has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.create(params[:comment].permit(:name, :body))
	    redirect_to post_path(@post)
	end
		

	def destroy
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.find(params[:id])
	    @comment.destroy
	    redirect_to post_path(@post)
	
	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index,:search]

    def index
      @post = Post.all.order("created_at DESC")
      # @posts = Post.recent_first.paginate(:page => params[:page], :per_page => 10)

      # @posts = Post.first(:order => 'id DESC')
      # render json: @post
    end

    def search
      # @post = Post.where("title LIKE?","%"+params[:q]+"%")
        # byebug
      @query  = params[:query]
      @post = Post.where("posts.title ILIKE ?",["%#{@query}%"])
      render "index"
    end 

    def show
      @post = Post.find(params[:id])
      render :show
      # render json: @post
    end

    def new
      @post = Post.new
    end

    def edit
    end

    def create
      @post = Post.new(post_params)
      @post.user = current_user

        respond_to do |format|
          if @post.save
            format.html { redirect_to post_url(@post), notice: "Book successfully created." }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_url(@post), notice: "Book successfully updated." }
          # format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy
        respond_to do |format|
          format.html { redirect_to posts_url, notice: "Book successfully deleted." }
          format.json { head :no_content }
        end
    end

    def upcoming_book
      @post = Post.all
    end


  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, :author, :b_subject, :image, :avatar, :attachment)
    end
  end

app/controllers/upcoming_books_controller.rb
class UpcomingBooksController < InheritedResources::Base
    before_action :set_post, only: %i[ show edit update destroy ]



    def index
      @upcoming_books = UpcomingBook.all
    end

    def show
      @upcoming_book = UpcomingBook.find(params[:id])
      render :show
      # render json: @upcoming_book
    end

    def new
      @upcoming_book = UpcomingBook.new
    end

    def edit
    end


    def create
      @upcoming_book = UpcomingBook.new(upcoming_book_params)
      # @upcoming_book.user = current_user

        respond_to do |format|
          if @upcoming_book.save
            format.html { redirect_to upcoming_book_url(@upcoming_book), notice: "Book successfully created." }
            # format.json { render :show, status: :created, location: @upcoming_book }
          else
            format.html { render :new, status: :unprocessable_entity }
            # format.json { render json: @upcoming_book.errors, status: :unprocessable_entity }
          end
        end
    end

    def update
      respond_to do |format|
        if @upcoming_book.update(upcoming_book_params)
          format.html { redirect_to upcoming_book_url(@upcoming_book), notice: "Book successfully updated." }
          # format.json { render :show, status: :ok, location: @upcoming_book }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @upcoming_book.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @upcoming_book.destroy
        respond_to do |format|
          format.html { redirect_to upcoming_books_url, notice: "Book successfully deleted." }
          format.json { head :no_content }
        end
    end

  private

    def set_post
      @upcoming_book = UpcomingBook.find(params[:id])
    end

    def upcoming_book_params
      params.require(:upcoming_book).permit(:title, :description, :author, :b_subject, :attachment, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upcoming_books_helper.rb
module UpcomingBooksHelper
end

app/views/comments/_comment.html.erb
<div class="col-lg-8 mb-">
      <div class="card shadow">
            <div class="card-body">
                  <table>
                        <tr>	
                        <td><p><b>Name: </b></p></td>
                        <td><p><%= comment.name %></p></td>
                        </tr>
                        <tr>
                        <td><p><b>Comment: </b></p></td>
                        <td><p><%= comment.body %></p></td>
                        </tr>
                        <p><%= time_ago_in_words(comment.created_at) %></p>
                        <%if current_user && current_user.admin %>
                        <td><p> <%= link_to 'Delete',[comment.post,comment],class: "btn btn-danger" ,method: :delete, data: {cofirm: 'Are you sure?'} %></p></td>
                        <%end%>
                  </table>
            </div>
      </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
</p>
<p>
	<%= f.submit %>
</p>

<%end%>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>  

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myshop</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
       <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      
        <%#= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
        <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= render partial: "posts/navbar" %>
      </head>
  <body>
  <!--   <body style="background-image: url(https://i.stack.imgur.com/90nGa.jpg);">
 -->
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

        <div class="container">
          <div class="row">
            <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="card shadow mb-3">
    <div class="card-body mx-auto ">	
        <h1>Welcome to Open Library</h1>
        <%= link_to 'See Available Books', posts_path ,class:"btn btn-outline-primary btn-lg mb-3 mx-auto"%>
        <%= link_to 'Upcoming Books',upcoming_books_path ,class:"btn btn-outline-primary btn-lg mb-3 mx-auto"%><br>


        <% if current_user %>
        <% else %>
        <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-primary" %>
        <%= link_to 'Sign in', new_user_session_path,  class:"btn btn-primary " %>
        <%end%>
    </div>
</div>

app/views/posts/_form.html.erb
        <%= image_tag @post.image if @post.image.attached? %>

<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :title , style: "display: block"%><br>
    <%= form.text_field :title , class: "form-control form-control-lg"%>
  </div>


  <div class="form-group mb-3">
    <%= form.label :author , style: "display: block"%><br>
    <%= form.text_field :author , class: "form-control form-control-lg" %>
  </div>  

  <div class="form-group mb-3">
    <%= form.label :subject , style: "display: block"%><br>
    <%= form.text_field :b_subject , class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description , style: "display: block" %><br>
    <%= form.text_area :description , class: "form-control form-control-lg"%>
  </div>  

   <div class="form-group mb-3">
    <%= form.label :image , style: "display: block" %><br>
    <%= form.file_field :image%>
  </div>     

  <div class="form-group mb-9">
    <%= form.label :attachment , style: "display: block" %><br>
    <%= form.file_field :attachment%>
  </div>  
  

  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-lg"%>
    <%= link_to 'Back', posts_path, class: "btn btn-outline-primary btn-lg" %>

  </div>
<% end %>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/pages" ><h3>Open Library</h3></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/pages"><h5>Home</h5> <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/posts"><h5>Available Books</h5></a>
       </li> 
        <li class="nav-item">
        <a class="nav-link" href="#"><h5>Request book</h5></a>
      </li>
      </li> 
        <li class="nav-item">
        <a class="nav-link" href="/upcoming_books"><h5>Upcoming books</h5></a>
      </li>
  
  </div>
</ul>
  

  <ul class="navbar-nav">
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/sign_in"><h5>Sign in</h5></a>
      </li>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/sign_out"><h5>Sign out</h5></a>
      </li>

     <!-- <form class="form-inline my-2 my-lg-0" action="/search" method="GET">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" method = "GET">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </ul>
</nav>

app/views/posts/_searchbar.html.erb
 <form class="form-inline" action="/search" method="GET">
<!--       <div class="form-group">
          <input type="search" placeholder="search your favourite Book" aria-label="Search" name="query" method = "GET" id="inputGroup-sizing-lg" class="form-control form-control-lg"><br>
      </div>
      <div class="form-group ">          
        <button class="btn btn-outline-success btn-lg" type="submit">Search</button>
      </div>  
 -->        


    <div class="container" class="justify-content-center">
    <div class="row height d-flex justify-content-center align-items-center">
        
          <table>
              <td><input type="search" class="form-control" placeholder="Find Book" aria-label="Search" name="query" method = "GET" class="form-control form-control-lg"> </td>
              <td><button class="btn btn-primary col-md-12  " type="submit" >Search</button> </td>
            
          </table>
            
       
    </div>
</div>
    </form>

app/views/posts/edit.html.erb
<div class="col-lg-8 mx-auto">
	<div class="card shadow">

		<div class="card-header">
			<h1 class="card-title">Edit Book</h1>
		</div>
		<div class="card-body">
			<%= render 'form', post: @post %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
  
<%= render  'posts/searchbar' %>  
   <p id="notice"><%= notice %></p>
      <p style = "color:green"><%= notice%></p>
        <div class="col-lg-8 mx-auto">
      <%if current_user && current_user.admin %> 

              <%= link_to 'Add New Book', new_post_path, class:"btn btn-outline-primary btn-lg mb-3"%> &emsp;

      <% end  %>              
        <h1>Available Books</h1>
        <div id="posts">
            <%@post.each do |post| %>
              <div class="card shadow mb-3">
                <div class="card-body">
                  <%= image_tag post.image if post.image.attached? %>
                  <%#= video_tag post.avatar if post.avatar.attached? %>
                 <p>
                  <strong>Title:</strong> <%= post.title %><br>
                  <strong>Author:</strong><%= post.author %><br>
                  <strong>Subject:</strong><%= post.b_subject %><br>
                  <!-- <strong>Id:</strong><%#= post.user_id %><br> -->
                 </p>
              </div>
           </div> 


          <table>
            <td>
              <%= link_to 'Book Details', post , class:"btn btn-primary btn-lg mb-3"%></td>
              <%#= link_to 'Book Details', post , class:"btn btn-primary btn-lg mb-3"%></td>
               <%if current_user && current_user.admin %> 
                <td><%= link_to 'Edit', edit_post_path(post), class:"btn btn-primary btn-lg mb-3" %>
                </td>
                <td><%= button_to 'Destroy', post, class:"btn btn-primary btn-lg mb-3", method: :delete, data: { confirm: 'Are you sure?' } %> </td>     
                <% end %>
            </table>
        <%end%>
            
      </div>
    </div>

app/views/posts/new.html.erb
<div class="col-lg-8 mx-auto">
	<div class="card shadow">

		<div class="card-header">
			<h1 class="card-title">Add New Book</h1>
		</div>
		<div class="card-body">
			<%= render 'form', post: @post %>
		</div>
	</div>
</div>

app/views/posts/search.html.erb
<h1>Search Results</h1>

<%= render @posts%>

app/views/posts/show.html.erb
<div class="col-lg-8 ">
    <div class="card shadow">
      <div class="card-body">
        <%= image_tag @post.image if @post.image.attached? %><br>
        <div width="150px" height= "150px">
          </div>
              <p>
                <strong>Title:</strong>
                <%= @post.title %>
              </p>
              <p>
                <strong>author:</strong>
                <%= @post.author %>
              </p>
              <p>
                <strong>Subject:</strong>
                <%= @post.b_subject %>
              </p>
              <!-- <p>
                <strong>User:</strong>
                <%#= @post.user_id %>
              </p> -->
              <p>
                <strong>Description:</strong>
                <%= @post.description %>
              </p>
       </div>
    </div>
</div>


    <div class="mt-5">
        <%= link_to 'Back', posts_path, class: "btn btn-outline-primary"%>
        <%#= link_to "Login to Download Book", class: "btn btn-warning" %>
        <% if current_user%> 
        <%=  link_to "Download book", @post.attachment_url, class: "btn btn-outline-primary" %>
        <% else %>
        <%= link_to "Please Signin/Signup to Download this book", class:"btn btn-outline-primary"%>
        <%end %>
    </div>
    <div>
        <h2><%= @post.comments.count %> Comments</h2><br>
        <%= render @post.comments %><br>
    </div>

    <div>
        <% if current_user %>
        <h3>Add a comment: </h3><br>
        <%= render  'comments/form' %>  
    </div>
        
<%end%>


<%#= link_to "Continue to Read Book", asset_path("rich-dad-poor-dad.pdf"),class: "btn btn-outline-primary"%>



        <!-- <iframe src=<%#= @post.avatar if @post.avatar.attached? %> width="600" height="780"><br> -->
          <%#= image_tag @post.avatar.url%>

app/views/upcoming_books/_form.html.erb
        <%= image_tag @upcoming_book.image if @upcoming_book.image.attached? %>

<%= form_with(model: upcoming_book, local: true) do |form| %>
  <% if upcoming_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upcoming_book.errors.count, "error") %> prohibited this upcoming_book from being saved:</h2>

      <ul>
        <% upcoming_book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
   <%= form.label :title , style: "display: block"%><br>
    <%= form.text_field :title , class: "form-control form-control-lg"%>
  </div>

   <div class="form-group mb-3">
    <%= form.label :description , style: "display: block" %><br>
    <%= form.text_area :description , class: "form-control form-control-lg"%>
  </div>  

  <div class="form-group mb-3">
    <%= form.label :author , style: "display: block"%><br>
    <%= form.text_field :author , class: "form-control form-control-lg" %>
  </div>  

   <div class="form-group mb-3">
    <%= form.label :subject , style: "display: block"%><br>
    <%= form.text_field :b_subject , class: "form-control form-control-lg" %>
  </div>

   <div class="form-group mb-3">
    <%= form.label :image , style: "display: block" %><br>
    <%= form.file_field :image%>
  </div> 
  
   <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/upcoming_books/edit.html.erb
<h1>Editing Upcoming Book</h1>

<%= render 'form', upcoming_book: @upcoming_book %>

<%= link_to 'Show', @upcoming_book %> |
<%= link_to 'Back', upcoming_books_path %>

app/views/upcoming_books/index.html.erb
  
<%#= render  'upcoming_books/searchbar' %>  
   <p id="notice"><%= notice %></p>
      <p style = "color:green"><%= notice%></p>
        <div class="col-lg-8 mx-auto">
      <%#if current_user && current_user.admin %> 

              <%= link_to 'Add New Book', new_upcoming_book_path, class:"btn btn-outline-primary btn-lg mb-3"%> &emsp;

      <%#end  %>              
        <h1>Books to be Released Soon</h1>
        <div id="upcoming_books">
            <%@upcoming_books.each do |upcoming_book| %>
              <div class="card shadow mb-3">
                <div class="card-body">
                  <%= image_tag upcoming_book.image if upcoming_book.image.attached? %>
                  <%#= video_tag upcoming_book.avatar if upcoming_book.avatar.attached? %>
                 <p>
                  <strong>Title:</strong> <%= upcoming_book.title %><br>
                  <strong>Author:</strong><%= upcoming_book.author %><br>
                  <strong>Subject:</strong><%= upcoming_book.b_subject %><br>
                  <!-- <strong>Id:</strong><%#= upcoming_book.user_id %><br> -->
                 </p>
              </div>
           </div> 


          <table>
            <td>
              <%= link_to 'Book Details', upcoming_book , class:"btn btn-primary btn-lg mb-3"%></td>
               <%#if current_user && current_user.admin %> 
                <td><%= link_to 'Edit', edit_upcoming_book_path(upcoming_book), class:"btn btn-primary btn-lg mb-3" %>
                </td>
                <td><%= button_to 'Destroy', upcoming_book, class:"btn btn-primary btn-lg mb-3", method: :delete, data: { confirm: 'Are you sure?' } %> </td>     
                <%# end %>
            </table>
        <%end%>
            
      </div>
    </div>



 <!--  <tbody>
    <%# @upcoming_books.each do |upcoming_book| %>
      <tr>
        <td><%#= upcoming_book.title %></td>
        <td><%#= upcoming_book.description %></td>
        <td><%#= upcoming_book.author %></td>
        <td><%#= upcoming_book.b_subject %></td>
        <td><%#= upcoming_book.attachment %></td>
        <td><%#= upcoming_book.user_id %></td>
        <td><%#= link_to 'Show', upcoming_book %></td>
        <td><%#= link_to 'Edit', edit_upcoming_book_path(upcoming_book) %></td>
        <td><%#= link_to 'Destroy', upcoming_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Upcoming Book', new_upcoming_book_path %> -->

app/views/upcoming_books/new.html.erb
<div class="col-lg-8 mx-auto">
	<div class="card shadow">

		<div class="card-header">
			<h1 class="card-title">Add New Book</h1>
		</div>
		<div class="card-body">
			<%= render 'form', upcoming_book: @upcoming_book %>
		</div>
	</div>
</div>

app/views/upcoming_books/show.html.erb
<div class="col-lg-8 ">
    <div class="card shadow">
      <div class="card-body">
        <%= image_tag @upcoming_book.image if @upcoming_book.image.attached? %><br>
        <div width="150px" height= "150px">
          </div>
              <p>
                <strong>Title:</strong>
                <%= @upcoming_book.title %>
              </p>
              <p>
                <strong>author:</strong>
                <%= @upcoming_book.author %>
              </p>
              <p>
                <strong>Subject:</strong>
                <%= @upcoming_book.b_subject %>
              </p>
              <!-- <p>
                <strong>User:</strong>
                <%#= @upcoming_book.user_id %>
              </p> -->
              <p>
                <strong>Description:</strong>
                <%= @upcoming_book.description %>
              </p>
       </div>
    </div>
</div>


    <div class="mt-5">
        <%= link_to 'Back', upcoming_books_path, class: "btn btn-outline-primary"%>
        <%#= link_to "Login to Download Book", class: "btn btn-warning" %>
        <%# if current_user%> 
        <%#=  link_to "Download book", @upcoming_book.attachment_url, class: "btn btn-outline-primary" %>
        <%# else %>
        <%#= link_to "Please Signin/Signup to Download this book", class:"btn btn-outline-primary"%>
        <%#end %>
    </div>
    <!-- <div>
        <h2><%#= @upcoming_book.comments.count %> Comments</h2><br>
        <%#= render @upcoming_book.comments %><br>
    </div>

    <div>
        <%# if current_user %>
        <h3>Add a comment: </h3><br>
        <%#= render  'comments/form' %>  
    </div>
        
<%#end%> -->


<%#= link_to "Continue to Read Book", asset_path("rich-dad-poor-dad.pdf"),class: "btn btn-outline-primary"%>



        <!-- <iframe src=<%#= @upcoming_book.avatar if @upcoming_book.avatar.attached? %> width="600" height="780"><br> -->
          <%#= image_tag @upcoming_book.avatar.url%>








<!-- <p id="notice"><%#= notice %></p>

<p>
  <strong>Title:</strong>
  <%#= @upcoming_book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%#= @upcoming_book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%#= @upcoming_book.author %>
</p>

<p>
  <strong>B subject:</strong>
  <%#= @upcoming_book.b_subject %>
</p>

<p>
  <strong>Attachment:</strong>
  <%#= @upcoming_book.attachment %>
</p>



<%#= link_to 'Edit', edit_upcoming_book_path(@upcoming_book) %> |
<%#= link_to 'Back', upcoming_books_path %>
 -->